--  Generated by Aquarius/Options
package Pdp11.Options is

   function Start return Natural;
   function Execute return Boolean;
   function Object return String;
   function Quiet return Boolean;
   function Source return String;
   function Test_Encoding return Boolean;
   function Time_Limit return Natural;
   function Trace return Boolean;
   function Warnings return Boolean;

end Pdp11.Options;
