--  Generated by Aquarius/Options
package Pdp11.Options is

   function Start return Natural;
   function Execute return Boolean;
   function Object return String;
   function Quiet return Boolean;
   function Source return String;
   function Test_Encoding return Boolean;
   function Time_Limit return Natural;
   function Limit_Speed return Boolean;
   function Trace return Boolean;
   function Warnings return Boolean;
   function Create_Disk return Boolean;
   function Write_Disk return Boolean;
   function Disk_Type return String;
   function Disk_File return String;
   function Disk_Address return String;

end Pdp11.Options;
